spring:
  datasource:
    hikari:
      data-source-properties:
        useServerPrepStmts: 'true'
        cacheResultSetMetadata: 'true'
        cacheServerConfiguration: 'true'
        cachePrepStmts: 'true'
        rewriteBatchedStatements: 'true'
        elideSetAutoCommits: 'true'
        useLocalSessionState: 'true'
        prepStmtCacheSize: '250'
        maintainTimeStats: 'false'
        prepStmtCacheSqlLimit: '2048'
      idle-timeout: '300000'
      maximum-pool-size: '10'
      connection-timeout: '50000'
      pool-name: ConnPool
      max-lifetime: '900000'
      connection-test-query: select 1 from dual
      minimum-idle: '10'
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gasp12024$
    username: gaspi
    url: jdbc:mysql://${MYSQL_HOST:104.154.193.94}:3306/gaspi
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
          nodeValue: TRACE